Repository kyma-project/hydroform, pull requests merged in 2021-08, with the labels that each got.

#335 Remove kazydek from CODEOWNERS & add NHingerl
  CODEOWNERS
Labels: area/documentation, size/XS, lgtm

#334 Add empty protocolsettings to the subscription CR
  function/pkg/resources/unstructured/subscription.go
  function/pkg/resources/unstructured/subscription_test.go
Labels: bug, area/serverless, size/XS, lgtm

#336 Support auth functionality in the `GitRepository` context
  function/pkg/resources/unstructured/git_repository.go
  function/pkg/resources/unstructured/git_repository_test.go
  function/pkg/workspace/cfg.go
Labels: enhancement, area/serverless, size/S, lgtm

#338 Check if override file exists
  parallel-install/pkg/overrides/overrides.go
  parallel-install/pkg/overrides/overrides_test.go
Labels: size/S, lgtm
