Repository kyma-project/hydroform, pull requests merged in 2021-02, with the labels that each got.

#179 Refactor logging in parallel-install lib
  parallel-install/example/example.go
  parallel-install/go.mod
  parallel-install/go.sum
  parallel-install/pkg/components/component.go
  parallel-install/pkg/components/components.go
  parallel-install/pkg/components/components_test.go
  parallel-install/pkg/components/prerequisites.go
  parallel-install/pkg/components/prerequisites_test.go
  parallel-install/pkg/config/config.go
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/core_test.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/engine/engine.go
  parallel-install/pkg/engine/engine_test.go
  parallel-install/pkg/helm/client.go
  parallel-install/pkg/helm/retry_with_backoff_test.go
  parallel-install/pkg/logger/logger.go
  parallel-install/pkg/overrides/overrides.go
  parallel-install/pkg/overrides/overrides_test.go
  parallel-install/pkg/prerequisites/prerequisites.go
Labels: area/installation

#186 Add library that allows running functions locally
  function/go.mod
  function/go.sum
  function/pkg/docker/automock/conn.go
  function/pkg/docker/automock/run.go
  function/pkg/docker/run.go
  function/pkg/docker/run_test.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
Labels: area/serverless

#194 Run functions locally examples
  function/examples/README.md
  function/examples/cmd/docker/run/main.go
  function/examples/go.mod
  function/examples/go.sum
Labels: WIP, area/serverless

#202 Hot deployment function code
  function/pkg/docker/run.go
  function/pkg/docker/run_test.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
Labels: WIP, area/serverless

#203 Hot deployment function code example
  function/examples/cmd/docker/run/main.go
  function/examples/go.mod
  function/examples/go.sum
Labels: WIP, area/serverless

#212 Send error updates
  parallel-install/pkg/components/component.go
  parallel-install/pkg/components/componentlist.go
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/deployment/overrideinterceptors.go
  parallel-install/pkg/deployment/overrides.go
  parallel-install/pkg/deployment/processupdate.go
  parallel-install/pkg/engine/engine.go
  parallel-install/pkg/engine/engine_test.go
Labels: area/cli, area/installation
