Repository kyma-project/hydroform, pull requests merged in 2021-03, with the labels that each got.

#205 Introduce Preinstaller in installation lib
  parallel-install/README.md
  parallel-install/example/example.go
  parallel-install/go.mod
  parallel-install/go.sum
  parallel-install/pkg/config/config.go
  parallel-install/pkg/config/config_test.go
  parallel-install/pkg/preinstaller/mocks/resourceappliermock.go
  parallel-install/pkg/preinstaller/mocks/resourcemanagermock.go
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
  parallel-install/pkg/preinstaller/resourceapplier.go
  parallel-install/pkg/preinstaller/resourceapplier_test.go
  parallel-install/pkg/preinstaller/resourcemanager.go
  parallel-install/pkg/preinstaller/resourcemanager_test.go
  parallel-install/pkg/test/data/resources/correct/crds/comp1/crd.yaml
  parallel-install/pkg/test/data/resources/correct/crds/comp2/crd.yaml
  parallel-install/pkg/test/data/resources/correct/namespaces/comp1/ns.yaml
  parallel-install/pkg/test/data/resources/correct/namespaces/comp2/ns.yaml
  parallel-install/pkg/test/data/resources/generic/correct/crd.yaml
  parallel-install/pkg/test/data/resources/generic/correct/ns.yaml
  parallel-install/pkg/test/data/resources/generic/incorrect/crd.yaml
  parallel-install/pkg/test/data/resources/generic/incorrect/ns.yaml
  parallel-install/pkg/test/data/resources/incorrect/crds/comp1/crd.yaml
  parallel-install/pkg/test/data/resources/incorrect/crds/comp2/crd.yaml
  parallel-install/pkg/test/data/resources/nocomponents/crds/.gitkeep
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp1/crd-correct.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp2/crd-correct.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp3/crd-incorrect.yaml
Labels: area/installation

#215 Set default namespace in component-list to kyma-system
  parallel-install/pkg/components/componentlist.go
Labels: area/installation

#217 Auto generated name
  function/pkg/generator/name_generator.go
  function/pkg/generator/name_generator_test.go
Labels: WIP, area/serverless

#219 Refactor parallel-install module
  parallel-install/go.sum
  parallel-install/pkg/components/prerequisites.go
  parallel-install/pkg/components/prerequisites_test.go
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/namespace/namespace.go
  parallel-install/pkg/prerequisites/prerequisites.go
Labels: area/installation

#216 Disallow applying inappropriate resource files, fix ResourceManager checking for resource
  parallel-install/example/example.go
  parallel-install/go.sum
  parallel-install/pkg/preinstaller/mocks/ResourceApplier.go
  parallel-install/pkg/preinstaller/mocks/ResourceManager.go
  parallel-install/pkg/preinstaller/mocks/ResourceParser.go
  parallel-install/pkg/preinstaller/mocks/resourceappliermock.go
  parallel-install/pkg/preinstaller/mocks/resourcemanagermock.go
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
  parallel-install/pkg/preinstaller/resourceapplier.go
  parallel-install/pkg/preinstaller/resourceapplier_test.go
  parallel-install/pkg/preinstaller/resourcemanager.go
  parallel-install/pkg/preinstaller/resourcemanager_test.go
  parallel-install/pkg/preinstaller/resourceparser.go
  parallel-install/pkg/preinstaller/resourceparser_test.go
  parallel-install/pkg/test/data/resources/generic/incorrect/notype.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp1/crd.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp2/crd.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp3/crd.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp4/ns.yaml
  parallel-install/pkg/test/data/resources/partiallycorrect/crds/comp5/ns.yaml
Labels: area/installation

#226 Fix Logger output for many logging arguments
  parallel-install/pkg/logger/logger.go
Labels: area/installation

#224 Fix manager examples
  function/examples/README.md
  function/examples/cmd/manager/main.go
  function/examples/internal/client/yaml_client.go
Labels: area/serverless

#228 Download Kyma sources
  parallel-install/README.md
  parallel-install/go.mod
  parallel-install/go.sum
  parallel-install/pkg/archive/archive.go
  parallel-install/pkg/archive/archive_test.go
  parallel-install/pkg/download/download.go
  parallel-install/pkg/download/download_test.go
  parallel-install/pkg/git/git.go
  parallel-install/pkg/git/git_test.go
Labels: area/installation
