Repository kyma-project/hydroform, pull requests merged in 2021-05, with the labels that each got.

#275 Rename master to main (leftover)
  .github/pull-request-template.md
Labels: area/documentation, lgtm, size/XS

#270 Coredns patch
  parallel-install/pkg/deployment/coredns.go
  parallel-install/pkg/deployment/coredns_test.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/deployment/overrideinterceptors.go
Labels: area/installation, lgtm, size/L

#277 Add verbose terraform option
  provision/internal/operator/terraform/operator.go
  provision/internal/operator/terraform/ops.go
  provision/types/ops.go
Labels: lgtm, size/M

#276 Add override interceptor for container registry
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/overrideinterceptors.go
  parallel-install/pkg/deployment/overrideinterceptors_test.go
Labels: lgtm, size/L

#280 Add coreDNS patch for K3s and interceptor improvements
  parallel-install/go.mod
  parallel-install/go.sum
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/coredns.go
  parallel-install/pkg/deployment/coredns_test.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/deployment/overrideinterceptors.go
  parallel-install/pkg/deployment/overrides.go
Labels: lgtm, size/L

#278 Add resources labeling
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
Labels: area/installation, lgtm, size/L

#282 Revert "Add resources labeling (#278)"
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
Labels: lgtm, size/L

#284 Expose recoverable attribute in InstallationError
  install/installation/errors.go
  install/installation/installation.go
  install/installation/installation_test.go
Labels: lgtm, size/M

#285 add test to resolve short commit hash
  parallel-install/pkg/git/resolve_test.go
Labels: lgtm, size/S

#283 Add labeling to CRD and NS resources in PreInstaller
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
Labels: area/installation, lgtm, size/L

#287 Remove further leftover resources
  parallel-install/pkg/deployment/deletion.go
Labels: lgtm, size/M

#289 Upgrade Wookiee beings in the CODEOWNERS file
  CODEOWNERS
Labels: area/serverless, enhancement, lgtm, size/XS

#288 Fix: Kyma sync function fails when the apirule AccessStrategie field is empty
  function/pkg/workspace/workspace.go
Labels: area/serverless, bug, lgtm, size/S

#291 Retries in installation library improved
  install/k8s/generic_client.go
  install/util/retry.go
  install/util/retry_test.go
  install/util/wait.go
  install/util/wait_test.go
Labels: lgtm, size/L

#286 Introduce CRDs uninstallation
  parallel-install/example/example.go
  parallel-install/pkg/config/config.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/preinstaller/mocks/ResourceManager.go
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
  parallel-install/pkg/preinstaller/resourceapplier.go
  parallel-install/pkg/preinstaller/resourceapplier_test.go
  parallel-install/pkg/preinstaller/resourcemanager.go
  parallel-install/pkg/preinstaller/resourcemanager_test.go
  parallel-install/pkg/preinstaller/resourceparser.go
Labels: area/installation, lgtm, size/XL

#292 Change alpine-kubectl image to k8s-tools
  install/installation/testdata/kyma-installer-upgrade.yaml
  install/installation/testdata/kyma-installer.yaml
  install/installation/testdata/tiller-upgrade.yaml
  install/installation/testdata/tiller.yaml
Labels: lgtm, size/S

#290 Remove interceptors that are now in kyma2 yaml
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/overrideinterceptors.go
Labels: lgtm, size/M

#293 Move PreInstaller to Deployment package
  parallel-install/example/example.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/mocks/ResourceApplier.go
  parallel-install/pkg/deployment/mocks/ResourceManager.go
  parallel-install/pkg/deployment/mocks/ResourceParser.go
  parallel-install/pkg/deployment/preinstaller.go
  parallel-install/pkg/deployment/preinstaller_test.go
  parallel-install/pkg/deployment/resourceapplier.go
  parallel-install/pkg/deployment/resourceapplier_test.go
  parallel-install/pkg/deployment/resourcemanager.go
  parallel-install/pkg/deployment/resourcemanager_test.go
  parallel-install/pkg/deployment/resourceparser.go
  parallel-install/pkg/deployment/resourceparser_test.go
Labels: area/installation, lgtm, size/L
