Repository kyma-project/hydroform, pull requests merged in 2021-07, with the labels that each got.

#328 Remove verbose flag param
  parallel-install/pkg/config/config.go
  parallel-install/pkg/deployment/deployment.go
Labels: lgtm, size/S

#331 Fix subscription structures
  function/pkg/resources/types/subscription.go
  function/pkg/resources/types/subscription_test.go
  function/pkg/resources/unstructured/subscription.go
  function/pkg/resources/unstructured/subscription_test.go
Labels: area/serverless, bug, lgtm, size/M

#332 make CRD rendering optional
  parallel-install/example/example.go
  parallel-install/pkg/deployment/templating.go
Labels: lgtm, size/S

#333 Limit sync to single namespace
  function/pkg/workspace/workspace.go
Labels: area/serverless, bug, lgtm, size/XS
