Repository kyma-project/hydroform, pull requests merged in 2021-04, with the labels that each got.

#239 Support branches as source
  parallel-install/pkg/git/git.go
Labels: area/cli

#244 Deploy single component
  parallel-install/pkg/config/componentlist.go
  parallel-install/pkg/config/componentlist_test.go
  parallel-install/pkg/git/git_test.go
Labels: area/installation

#251 fix helm kubeconfig
  parallel-install/example/example.go
  parallel-install/pkg/components/components.go
  parallel-install/pkg/config/config.go
  parallel-install/pkg/config/config_test.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/helm/client.go
  parallel-install/pkg/helm/metadataprovider.go
  parallel-install/pkg/helm/metadataprovider_test.go
  parallel-install/pkg/preinstaller/preinstaller.go
  parallel-install/pkg/preinstaller/preinstaller_test.go
  parallel-install/pkg/preinstaller/resourcemanager.go
  parallel-install/pkg/preinstaller/resourcemanager_test.go
Labels: area/installation

#242 Add ApiRuleOperator
  function/pkg/operator/apirule_operator.go
  function/pkg/operator/apirule_operator_test.go
  function/pkg/operator/generic_operator.go
  function/pkg/resources/types/api_rule.go
  function/pkg/resources/unstructured/api_rule.go
  function/pkg/resources/unstructured/api_rule_test.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: area/serverless

#254 New Installation: ensure consistent release state before upgrade/install
  parallel-install/go.sum
  parallel-install/pkg/helm/client.go
Labels: area/installation

#258 Remove node10 add node14
  function/examples/README.md
  function/examples/cmd/workspace/sync/main.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
  function/pkg/workspace/writer_provider_test.go
Labels: area/serverless

#263 Interceptors batteries included
  parallel-install/go.sum
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/deployment/overrideinterceptors.go
  parallel-install/pkg/deployment/overrideinterceptors_test.go
  parallel-install/pkg/logger/logger.go
  parallel-install/pkg/test/data/deployment-global-overrides-for-remote-cluster.yaml
Labels: area/installation, do-not-merge/hold, lgtm, size/XL

#273 Improve variable naming
  parallel-install/pkg/git/clone.go
Labels: lgtm, size/S
