Repository kyma-project/hydroform, pull requests merged in 2021-06, with the labels that each got.

#296 Make prerequisites fail fast
  parallel-install/pkg/deployment/deployment.go
Labels: lgtm, size/S

#299 Reverse prerequisites order when uninstalling
  parallel-install/pkg/components/components.go
  parallel-install/pkg/components/components_test.go
  parallel-install/pkg/deployment/core_test.go
  parallel-install/pkg/engine/engine.go
  parallel-install/pkg/engine/engine_test.go
Labels: lgtm, size/M

#295 Refactor overrides to have all in 1 pkg and improve registry interceptor
  parallel-install/example/example.go
  parallel-install/pkg/deployment/core.go
  parallel-install/pkg/deployment/coredns.go
  parallel-install/pkg/deployment/coredns_test.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/deployment_test.go
  parallel-install/pkg/deployment/gardener/gardener.go
  parallel-install/pkg/deployment/k3d/k3d.go
  parallel-install/pkg/deployment/overrides.go
  parallel-install/pkg/deployment/overrides_test.go
  parallel-install/pkg/overrides/interceptors.go
  parallel-install/pkg/overrides/interceptors_test.go
  parallel-install/pkg/overrides/overrides.go
  parallel-install/pkg/overrides/overrides_test.go
  parallel-install/pkg/overrides/provider.go
  parallel-install/pkg/overrides/provider_test.go
Labels: lgtm, size/XXL

#300 Hide PreInstaller implementation structs, improve tests
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/preinstaller.go
  parallel-install/pkg/deployment/preinstaller_test.go
Labels: area/installation, lgtm, size/L

#304 Delete Ory Oauth Client finalizer during uninstallation
  parallel-install/pkg/deployment/deletion.go
Labels: lgtm, size/S

#305 Add nil checks to prevent crashing
  parallel-install/pkg/deployment/deletion.go
Labels: lgtm, size/M

#306 Added tests for new reuse helm values option
  parallel-install/pkg/components/components_test.go
  parallel-install/pkg/helm/client.go
  parallel-install/pkg/helm/client_test.go
Labels: lgtm, size/M

#307 Remove all remaining custom resource finalizers
  parallel-install/go.mod
  parallel-install/go.sum
  parallel-install/pkg/deployment/deletion.go
Labels: lgtm, size/L

#308 Delete finalizers from all namespaces and serverless secrets
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/deployment/deletion_test.go
Labels: lgtm, size/L

#309 Delete all Custom Resources during uninstallation
  parallel-install/pkg/config/config.go
  parallel-install/pkg/deployment/deletion.go
  parallel-install/pkg/helm/client.go
Labels: lgtm, size/L

#310 Move finalizer deletion into a function
  parallel-install/pkg/deployment/deletion.go
Labels: lgtm, size/L

#311 Add retries for finalizer deletion
  parallel-install/pkg/deployment/deletion.go
Labels: lgtm, size/M

#319 drop support for creating namespaces in preinstaller (#314)
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/deployment/preinstaller.go
  parallel-install/pkg/deployment/preinstaller_test.go
  parallel-install/pkg/test/data/resources/correct/namespaces/comp1/ns.yaml
  parallel-install/pkg/test/data/resources/correct/namespaces/comp2/ns.yaml
Labels: lgtm, size/L

#318 Add templating support
  parallel-install/example/example.go
  parallel-install/pkg/components/component.go
  parallel-install/pkg/components/manifest.go
  parallel-install/pkg/debug/manifest.go
  parallel-install/pkg/deployment/core_test.go
  parallel-install/pkg/deployment/preinstaller.go
  parallel-install/pkg/deployment/preinstaller_test.go
  parallel-install/pkg/deployment/templating.go
  parallel-install/pkg/engine/engine.go
  parallel-install/pkg/engine/engine_test.go
  parallel-install/pkg/helm/client.go
Labels: lgtm, size/L

#323 Delete kyma src before cloning repo
  parallel-install/pkg/git/clone.go
Labels: lgtm, size/XS

#324 Add JeremyHarisch as code owner
  CODEOWNERS
  OWNERS
Labels: lgtm, size/XS

#325 Added Jeremy to Hydroform?Parallel-Install as CodeOwner
  CODEOWNERS
Labels: lgtm, size/XS

#315 Add Verbose param to silence K8 deprecation warnings
  parallel-install/pkg/config/config.go
  parallel-install/pkg/deployment/deployment.go
Labels: lgtm, size/S

#322 Drop support for reading overrides from ConfigMap
  parallel-install/pkg/deployment/core_test.go
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/engine/engine.go
  parallel-install/pkg/overrides/provider.go
  parallel-install/pkg/overrides/provider_test.go
Labels: lgtm, size/L

#321 Add python39 runtime
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: lgtm, size/L

#326 Verbose deploy
  parallel-install/pkg/deployment/deployment.go
Labels: lgtm, size/XS

#312 Implementation of jobManager
  parallel-install/go.mod
  parallel-install/go.sum
  parallel-install/pkg/deployment/deployment.go
  parallel-install/pkg/engine/engine.go
  parallel-install/pkg/jobmanager/README.md
  parallel-install/pkg/jobmanager/certificatesJobs.go
  parallel-install/pkg/jobmanager/certificatesJobs_test.go
  parallel-install/pkg/jobmanager/jobmanager.go
  parallel-install/pkg/jobmanager/jobmanager_test.go
  parallel-install/pkg/jobmanager/loggingJobs.go
  parallel-install/pkg/jobmanager/loggingJobs_test.go
  parallel-install/pkg/jobmanager/pictures/migration-logic-diagram.png
Labels: area/installation, lgtm, size/XL

#327 update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS
