Repository kyma-project/hydroform, pull requests merged in 2022-06, with the labels that each got.

#365 Fix function examples
  function/examples/cmd/docker/run/main.go
  function/examples/cmd/workspace/sync/main.go
  function/pkg/docker/run_test.go
  function/pkg/docker/runtimes/runtimes.go
Labels: size/M, lgtm

#364 Add nodejs16 to allowed runtimes
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: size/L, lgtm

#367 Upgrade gardener to latest
  provision/go.mod
  provision/go.sum
  provision/internal/operator/native/gardener/gardener.go
Labels: size/L, lgtm

#366 Add k8s app name label to function
  function/pkg/resources/unstructured/function.go
  function/pkg/resources/unstructured/function_test.go
Labels: size/M, lgtm

#370 Bump containerd
  function/go.mod
  function/go.sum
Labels: size/S, lgtm

#372 Upgrade gardener to latest release
  provision/go.mod
  provision/go.sum
Labels: size/XS, lgtm

#369 Update function on label or annotation change 368
  function/pkg/operator/operator.go
  function/pkg/operator/operator_test.go
Labels: size/XL, lgtm
