Repository kyma-project/hydroform, pull requests merged in 2022-11, with the labels that each got.

#386 Kyma function spec
  function/pkg/operator/generic_operator.go
  function/pkg/resources/types/function.go
  function/pkg/resources/types/git_repository.go
  function/pkg/resources/unstructured/api_rule.go
  function/pkg/resources/unstructured/function.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/resources/unstructured/git_repository.go
  function/pkg/resources/unstructured/git_repository_test.go
  function/pkg/workspace/synchronise.go
  function/pkg/workspace/synchronise_test.go
  function/pkg/workspace/workspace_test.go
Labels: size/L, lgtm

#387 Delete unused files and revert changes made by mistake
  function/pkg/operator/generic_operator.go
  function/pkg/resources/unstructured/git_repository.go
  function/pkg/resources/unstructured/git_repository_test.go
Labels: area/serverless, size/L, lgtm

#388 Update synchronise to align with new Cfg
  function/pkg/operator/generic_operator.go
  function/pkg/workspace/synchronise.go
  function/pkg/workspace/synchronise_test.go
Labels: area/serverless, size/L, lgtm

#389 Security bumps for function
  function/go.mod
  function/go.sum
Labels: size/M, lgtm

#390 Quick update to function's Apirule
  function/pkg/resources/types/api_rule.go
  function/pkg/resources/unstructured/api_rule.go
  function/pkg/resources/unstructured/api_rule_test.go
  function/pkg/workspace/synchronise.go
Labels: kind/bug, area/serverless, size/M, lgtm

#391 Bump golang.org/x/net
  function/go.mod
  function/go.sum
Labels: size/S, lgtm

#392 Fix Function Synchronise
  function/pkg/resources/types/api_rule.go
  function/pkg/resources/unstructured/function.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/synchronise.go
Labels: size/M, lgtm
