Repository kyma-project/hydroform, pull requests merged in 2022-04, with the labels that each got.

#353 Upgrade function/mod.go
  function/go.mod
  function/go.sum
Labels: area/serverless, size/XL, lgtm, area/security

#351 Support `customRuntimeImage` field
  function/pkg/resources/types/function.go
  function/pkg/resources/unstructured/function.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/synchronise.go
Labels: area/serverless, size/M, lgtm

#354 Fix whitesource complain
  provision/go.mod
  provision/go.sum
Labels: size/M, lgtm

#355 Get rid of the `kubeless-npm-install.sh` file in the `hydroform/function` module
  function/pkg/docker/run_test.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
Labels: area/serverless, size/M, lgtm

#352 Fix for local functions running from subfolders
  function/pkg/docker/automock/run.go
  function/pkg/docker/run.go
  function/pkg/docker/run_test.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
Labels: area/cli, size/L, lgtm

#359 Update gardener to the latest release
  provision/examples/gardener/aws/main.go
  provision/examples/gardener/azure/main.go
  provision/examples/gardener/gcp/main.go
  provision/go.mod
  provision/go.sum
Labels: size/M, lgtm

#358 Remove the deprecated install module
  CODEOWNERS
  Makefile
  README.md
  install/README.md
  install/before-commit.sh
  install/config/converter.go
  install/config/converter_test.go
  install/config/testdata/config.yaml
  install/example/example.go
  install/go.mod
  install/go.sum
  install/installation/configuration.go
  install/installation/configuration_test.go
  install/installation/errors.go
  install/installation/errors_test.go
  install/installation/installation.go
  install/installation/installation_test.go
  install/installation/main_test.go
  install/installation/options.go
  install/installation/options_test.go
  install/installation/testdata/kyma-installer-cr.yaml
  install/installation/testdata/kyma-installer-upgrade-cr.yaml
  install/installation/testdata/kyma-installer-upgrade.yaml
  install/installation/testdata/kyma-installer.yaml
  install/installation/testdata/tiller-upgrade.yaml
  install/installation/testdata/tiller.yaml
  install/k8s/generic_client.go
  install/k8s/generic_client_test.go
  install/k8s/mocks/RESTMapper.go
  install/k8s/testdata/k8s-resources.yaml
  install/k8s/yaml_parser.go
  install/k8s/yaml_parser_test.go
  install/scheme/scheme.go
  install/util/maputils.go
  install/util/maputils_test.go
  install/util/retry.go
  install/util/retry_test.go
  install/util/wait.go
  install/util/wait_test.go
Labels: size/XXL, lgtm
