Repository kyma-project/hydroform, pull requests merged in 2022-05, with the labels that each got.

#360 Migrate go mods from incubator to kyma project
  Makefile
  function/README.md
  function/examples/go.sum
  function/go.mod
  function/pkg/docker/run_test.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/manager/manager.go
  function/pkg/manager/manager_test.go
  function/pkg/manager/options.go
  function/pkg/operator/apirule_operator.go
  function/pkg/operator/apirule_operator_test.go
  function/pkg/operator/automock/operator.go
  function/pkg/operator/generic_operator.go
  function/pkg/operator/generic_operator_test.go
  function/pkg/operator/operator.go
  function/pkg/operator/operator_test.go
  function/pkg/operator/subscription_operator.go
  function/pkg/operator/subscription_operator_test.go
  function/pkg/resources/unstructured/api_rule.go
  function/pkg/resources/unstructured/api_rule_test.go
  function/pkg/resources/unstructured/function.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/resources/unstructured/git_repository.go
  function/pkg/resources/unstructured/git_repository_test.go
  function/pkg/resources/unstructured/subscription.go
  function/pkg/resources/unstructured/subscription_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/synchronise.go
  function/pkg/workspace/synchronise_test.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
  function/pkg/workspace/writer_provider_test.go
  provision/README.md
  provision/examples/gardener/aws/main.go
  provision/examples/gardener/azure/main.go
  provision/examples/gardener/gcp/main.go
  provision/go.mod
  provision/internal/azure/azure.go
  provision/internal/azure/azure_test.go
  provision/internal/gardener/gardener.go
  provision/internal/gardener/gardener_test.go
  provision/internal/gcp/gcp.go
  provision/internal/gcp/gcp_test.go
  provision/internal/kind/kind.go
  provision/internal/kind/kind_test.go
  provision/internal/operator/mocks/operator.go
  provision/internal/operator/native/gardener/gardener.go
  provision/internal/operator/native/operator.go
  provision/internal/operator/operator.go
  provision/internal/operator/unknown.go
  provision/provision.go
Labels: size/L, lgtm

#362 Move labels from spec to metadata in function
  function/before-commit.sh
  function/pkg/resources/unstructured/function.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/workspace/synchronise.go
  function/pkg/workspace/synchronise_test.go
Labels: area/cli, area/serverless, size/M, lgtm

#361 Migrate function examples module away from incubator
  function/examples/cmd/callbacks/post/main.go
  function/examples/cmd/callbacks/pre/main.go
  function/examples/cmd/docker/run/main.go
  function/examples/cmd/manager/main.go
  function/examples/cmd/operator/apply/main.go
  function/examples/cmd/operator/delete/main.go
  function/examples/cmd/workspace/init/main.go
  function/examples/cmd/workspace/sync/main.go
  function/examples/go.mod
  function/examples/go.sum
Labels: size/XXL, lgtm
