Repository kyma-project/hydroform, pull requests merged in 2022-03, with the labels that each got.

#346 Reflect workspace function schema
  function/go.mod
  function/go.sum
  function/pkg/workspace/cfg.go
  function/pkg/workspace/schema.go
Labels: size/S, lgtm

#347 Refactor workspace package
  function/pkg/resources/unstructured/function_test.go
  function/pkg/resources/unstructured/subscription_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/empty_file.go
  function/pkg/workspace/file.go
  function/pkg/workspace/synchronise.go
  function/pkg/workspace/synchronise_test.go
  function/pkg/workspace/templated_file.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
  function/pkg/workspace/writer_provider.go
  function/pkg/workspace/writer_provider_test.go
  function/pkg/workspace/ws_nodejs.go
  function/pkg/workspace/ws_python.go
Labels: area/cli, area/serverless, size/L, lgtm

#348 refactor: remove terraform dependency
  provision/examples/README.md
  provision/examples/azure/README.md
  provision/examples/azure/main.go
  provision/examples/gardener/aws/main.go
  provision/examples/gardener/azure/main.go
  provision/examples/gardener/gcp/main.go
  provision/examples/gcp/README.md
  provision/examples/gcp/assets/add-details-gke.png
  provision/examples/gcp/assets/assign-roles.png
  provision/examples/gcp/assets/create-account-gke.png
  provision/examples/gcp/assets/create-account-key-gke.png
  provision/examples/gcp/main.go
  provision/examples/kind/README.md
  provision/examples/kind/main.go
  provision/go.mod
  provision/go.sum
  provision/internal/azure/azure.go
  provision/internal/azure/azure_test.go
  provision/internal/gardener/gardener.go
  provision/internal/gardener/gardener_test.go
  provision/internal/gcp/gcp.go
  provision/internal/gcp/gcp_test.go
  provision/internal/kind/kind.go
  provision/internal/kind/kind_test.go
  provision/internal/operator/mocks/operator.go
  provision/internal/operator/native/gardener/aws/control_plane.go
  provision/internal/operator/native/gardener/aws/infrastructure.go
  provision/internal/operator/native/gardener/azure/control_plane.go
  provision/internal/operator/native/gardener/azure/infrastructure.go
  provision/internal/operator/native/gardener/gardener.go
  provision/internal/operator/native/gardener/gcp/control_plane.go
  provision/internal/operator/native/gardener/gcp/infrastructure.go
  provision/internal/operator/native/operator.go
  provision/internal/operator/operator.go
  provision/internal/operator/unknown.go
  provision/provision.go
  provision/types/cluster.go
  provision/types/ops.go
  terraform/files.go
  terraform/filter.go
  terraform/filter_test.go
  terraform/gardener.go
  terraform/operator.go
  terraform/ops.go
  terraform/ops_test.go
  terraform/tfcmd.go
  terraform/tfcmd_test.go
  terraform/timeouts.go
  terraform/timeouts_test.go
  terraform/ui.go
  terraform/ui_test.go
Labels: size/XXL, lgtm

#349 Bump go version to `1.18`
  function/go.mod
  function/go.sum
Labels: area/serverless, size/M, lgtm, area/security
