Repository kyma-project/hydroform, pull requests merged in 2022-10, with the labels that each got.

#380 Update golang.org/x/text version to v0.3.8
  provision/go.mod
  provision/go.sum
Labels: size/M, lgtm

#383 CVE-2022-27664, update version of golang.org/x/net
  provision/go.mod
  provision/go.sum
Labels: size/S, lgtm

#382 remove deprecated nodejs12
  function/examples/cmd/docker/run/main.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/resources/unstructured/subscription_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/synchronise_test.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: size/L, lgtm
