Repository kyma-project/hydroform, pull requests merged in 2023-03, with the labels that each got.

#403 upgrade golang.org/x/net to v0.7.0
  function/go.mod
  function/go.sum
Labels: size/S, lgtm

#402 Add nodejs18 runtime
  function/examples/cmd/docker/run/main.go
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: area/cli, area/serverless, size/L, lgtm

#405 updated codeowners
  CODEOWNERS
  OWNERS
Labels: size/S, lgtm

#404 Fix security vulnerabilities
  function/go.mod
  function/go.sum
  hack/verify-lint.sh
  provision/go.mod
  provision/go.sum
Labels: size/XXL, lgtm
