Repository kyma-project/hydroform, pull requests merged in 2023-02, with the labels that each got.

#396 Fix NPD in waitForShoot
  provision/go.mod
  provision/go.sum
  provision/internal/operator/native/gardener/gardener.go
  provision/internal/operator/native/gardener/gardener_test.go
Labels: size/L, lgtm

#400 Update list of function package creators
  function/pkg/generator/name_generator.go
Labels: area/serverless, size/XS, lgtm

#401 update deprecated linter configuration and fix linter error
  function/pkg/docker/run_test.go
  function/pkg/resources/types/api_rule.go
  function/pkg/workspace/workspace_test.go
  hack/verify-lint.sh
  provision/action/actions.go
  provision/internal/azure/azure.go
  provision/internal/azure/azure_test.go
  provision/internal/gardener/gardener.go
  provision/internal/gardener/gardener_test.go
  provision/internal/gcp/gcp.go
  provision/internal/gcp/gcp_test.go
  provision/internal/kind/kind.go
  provision/internal/kind/kind_test.go
  provision/provision.go
Labels: size/L, lgtm

#397 Add new subscription for v1alpha2
  function/pkg/operator/generic_operator.go
  function/pkg/operator/operator.go
  function/pkg/operator/operator_test.go
  function/pkg/operator/subscription_operator.go
  function/pkg/operator/subscription_operator_test.go
  function/pkg/operator/types/types.go
  function/pkg/resources/types/subscription_v1alpha1.go
  function/pkg/resources/types/subscription_v1alpha1_test.go
  function/pkg/resources/types/subscription_v1alpha2.go
  function/pkg/resources/types/subscription_v1alpha2_test.go
  function/pkg/resources/unstructured/function_test.go
  function/pkg/resources/unstructured/subscription.go
  function/pkg/resources/unstructured/subscription_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/synchronise.go
  function/pkg/workspace/synchronise_test.go
  function/pkg/workspace/workspace_test.go
  provision/internal/azure/azure.go
  provision/internal/operator/native/gardener/gardener.go
Labels: size/XL, lgtm
