Repository kyma-project/hydroform, pull requests merged in 2024-03, with the labels that each got.

#442 Add Python 3.12 support
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: area/serverless, size/L, lgtm, kind/chore, cla: yes

#443 Add nodejs20 runtime
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: size/M, lgtm, cla: yes

#446 Fix image for nodejs20
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
Labels: size/XS, lgtm, cla: yes

#448 Fix nodejs20 runtime
  function/pkg/docker/runtimes/runtimes.go
Labels: size/XS, lgtm, cla: yes

#447 Remove Nodejs16 support
  function/pkg/docker/runtimes/runtimes.go
  function/pkg/docker/runtimes/runtimes_test.go
  function/pkg/resources/types/runtimes.go
  function/pkg/resources/unstructured/subscription_test.go
  function/pkg/workspace/cfg.go
  function/pkg/workspace/synchronise_test.go
  function/pkg/workspace/workspace.go
  function/pkg/workspace/workspace_test.go
Labels: size/L, lgtm, cla: yes
